### ISSUE TITLE
Licence GPL vs. EPL

### ISSUE THREAD

**Issue by whilo** [log0ymxm/clj-auto-diff#5]
The licence for R6RS-ad is GPL it seems. Is your implementation a clean-room implementation of the papers or have you directly ported the code? Sadly the EPL and GPL are incompatible and the Clojure core team has not addressed that issue yet. I am looking into an autodifferentiation engine for neural network backpropagation algorithms similar to tensorflow, theano or torch and would like to leverage Lisp's large heritage in this area, but am unsure how to proceed. sicmutils for Clojure share the same problem: https://github.com/littleredcomputer/sicmutils/issues/31

**Comment by log0ymxm** [comment]
Ah, this is a direct port and the license needs to be corrected.

**Comment by whilo** [comment]
This is not enough, EPL and GPL are incompatible, so in effect the library is not redistributable (e.g. in a jar file etc.). I have contacted Jeffrey Mark Sisking and he replied:

~~~
Note that I am not the author/owner of SCMUTILS. You would need to contact
Gerry Sussman (gjs@mit.edu) for that.

I am the author/owner of R6RS-AD. I would be happy to relicense R6RS-AD under
both LPGL and MIT. I am also happy to provide an exception EPL-based libraries
to the GPL.

You can consider this email as executing such relicensing.

I suggest that you pick an appropriate licence, e.g. MIT and assume R6RS-AD to be under MIT.
~~~

**Comment by paul-english** [comment]
Yeah, you're right it is incompatible. I also confirmed with @qobi on this and relicensed accordingly thanks for reaching out about this.
